server:
  port: 8001


mybatis:
  type-aliases-package: com.study.springcloud.dao
  config-location:
    classpath:mybatis/mybatis-config.xml #注意这里classpath:后没有空格
  mapper-locations:
    classpath:mybatis/mapper/*.xml  #注意这里classpath:后没有空格


# spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cloud01?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://127.0.0.1:3306/cloud01?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: baoqy